version: "3.8"

services:
  waha:
    restart: always
    image: devlikeapro/waha-plus:chrome

    container_name: waha

    # DNS para evitar problemas de rede
    dns:
      - 1.1.1.1
      - 8.8.8.8

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'

    ports:
      # Porta externa da Railway deve ser 3000
      - '3000:3000'

    volumes:
      # Sessões locais (se não usar MongoDB)
      - './.sessions:/app/.sessions'

      # Pasta de mídia
      - './.media:/app/.media'

    env_file:
      - .env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
  minio_data: {}
  pg_data: {}
