version: "3.8"

services:
  # Painel para escanear o QR Code
  waha-dashboard:
    image: devlikeapro/waha-plus:chrome
    container_name: waha-dashboard
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - WAHA_WORKER_ID=waha-dashboard

  # Instância principal do WhatsApp
  waha1:
    image: devlikeapro/waha-plus:chrome
    container_name: waha1
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - './.sessions:/app/.sessions'
    env_file:
      - .env
    environment:
      - WAHA_WORKER_ID=waha1
      - WAHA_BASE_URL=http://localhost:3001
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_SESSIONS_MONGO_URL=mongodb://mongodb:27017
      - WHATSAPP_HOOK_URL=https://teste-production-ec11.up.railway.app/webhook/aca33175-5e48-4c53-9167-21589c89d3e4
      - WHATSAPP_HOOK_EVENTS=message

  # MongoDB (armazenamento de sessões)
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}
